[project]
name = "exp-trckr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-filter>=25.2",
    "django>=5.2.8",
    "djangorestframework>=3.16.1",
    "markdown>=3.10",
    "django-environ>=0.12.0",
    "psycopg2-binary>=2.9.11",
    "drf-spectacular>=0.29.0",
]
