import pytest
from django.urls import reverse
from rest_framework.test import APIClient

from apps.finance.tests.factories import UserFactory, AccountFactory
from apps.finance.models.account import Account


@pytest.mark.django_db
class TestAccountViewSet:

    @pytest.fixture
    def client(self):
        return APIClient()

    @pytest.fixture
    def user(self):
        return UserFactory()

    @pytest.fixture
    def auth_client(self, client, user):
        client.force_authenticate(user)
        return client

    #
    # LIST
    #
    def test_list_accounts(self, auth_client, user):
        AccountFactory.create_batch(3, user=user)
        # other user's accounts, should NOT appear
        AccountFactory.create_batch(2)

        url = reverse("account-list")  # generated by router
        response = auth_client.get(url)

        assert response.status_code == 200
        assert len(response.data) == 3
        assert all(acc["id"] for acc in response.data)

    #
    # RETRIEVE
    #
    def test_retrieve_account(self, auth_client, user):
        account = AccountFactory(user=user)

        url = reverse("account-detail", args=[account.id])
        response = auth_client.get(url)

        assert response.status_code == 200
        assert response.data["id"] == str(account.id)
        assert response.data["name"] == account.name

    #
    # CREATE
    #
    def test_create_account(self, auth_client, user):
        url = reverse("account-list")

        payload = {
            "name": "My Account",
            "type": "main"
        }

        response = auth_client.post(url, payload, format="json")

        assert response.status_code == 201
        assert response.data["name"] == "My Account"
        assert response.data["balance"] == "0.00"

        created = Account.objects.get(id=response.data["id"])
        assert created.user == user

    #
    # UPDATE
    #
    def test_update_account(self, auth_client, user):
        account = AccountFactory(user=user)

        url = reverse("account-detail", args=[account.id])
        payload = {
            "name": "Updated",
            "type": "cash",
            "balance": str(account.balance),  # still required by serializer
        }

        response = auth_client.put(url, payload, format="json")

        assert response.status_code == 200
        assert response.data["name"] == "Updated"
        account.refresh_from_db()
        assert account.name == "Updated"

    #
    # PARTIAL UPDATE
    #
    def test_partial_update_account(self, auth_client, user):
        account = AccountFactory(user=user)

        url = reverse("account-detail", args=[account.id])
        payload = {"name": "Partially Updated"}

        response = auth_client.patch(url, payload, format="json")

        assert response.status_code == 200
        assert response.data["name"] == "Partially Updated"

    #
    # DESTROY (soft delete)
    #
    def test_destroy_account_soft_delete(self, auth_client, user):
        account = AccountFactory(user=user)

        url = reverse("account-detail", args=[account.id])
        response = auth_client.delete(url)

        assert response.status_code == 204

        account.refresh_from_db()
        assert account.is_deleted is True

        # ensure queryset excludes deleted
        url = reverse("account-list")
        response = auth_client.get(url)
        assert len(response.data) == 0
